openapi: 3.0.0
info:
  title: api-client
  description: 汎用的な API 定義
  version: 1.0.0
servers:
  - url: https://example.com
paths:
  /example:
    get:
      responses:
        '200':
          description: OK.
components:
  schemas:
    ErrorResponse:
      $ref: ./components/error-response.yaml
    UnauthorizedErrorResponse:
      $ref: ./components/401-unauthorized-error-response.yaml
